wip

diff --git a/rust/Earthfile b/rust/Earthfile
--- a/rust/Earthfile
+++ b/rust/Earthfile
@@ -2,14 +2,8 @@ VERSION 0.8
 
 IMPORT github.com/input-output-hk/catalyst-ci/earthly/rust:v3.2.10 AS rust-ci
 
-# sync-cfg: Synchronize local config with CI version.
-# Must be run by the developer manually.
-sync-cfg:
-    DO rust-ci+SYNC_STD_CFG
-
-# builder : Set up our target toolchains, and copy our files.
-builder:
-    DO rust-ci+SETUP
+COPY_SRC:
+    FUNCTION
 
     COPY Cargo.toml clippy.toml deny.toml rustfmt.toml .
     COPY --dir .cargo .config \
@@ -20,6 +14,34 @@ builder:
                 cbork-abnf-parser \
                 cbork-cddl-parser \
                 hermes-ipfs .
+
+FINGERPRINT_SRC:
+    FUNCTION
+
+    ARG WHENCE=..
+    ARG DIR=build
+    ARG FINGERPRINT=src_fingerprint.txt
+
+    RUN cd $WHENCE; \
+        tar -C ./ -cf - --sort=name --mtime='UTC 2019-01-01' --group=0 --owner=0 --numeric-owner $DIR \
+        | sha256sum  > $FINGERPRINT
+    RUN cat $WHENCE/$FINGERPRINT
+
+# sync-cfg: Synchronize local config with CI version.
+# Must be run by the developer manually.
+sync-cfg:
+    DO rust-ci+SYNC_STD_CFG
+
+# builder : Set up our target toolchains, and copy our files.
+builder:
+    DO rust-ci+SETUP
+
+    # Cached copy of the source we build.
+    DO +COPY_SRC
+
+    # Generate Checksums of the source
+    DO +FINGERPRINT_SRC
+    SAVE ARTIFACT ../src_fingerprint.txt 
 
 # check : Run basic check.
 check:
@@ -42,6 +64,24 @@ build:
 
     SAVE ARTIFACT target/$TARGETARCH/doc doc
     SAVE ARTIFACT target/release/cbork cbork
+
+# build-src-check: Check for any caching issues with the source we are building against.
+check-builder-src-cache:
+    FROM +builder
+
+    COPY +builder-src/src_fingerprint.txt .
+
+    RUN --no-cache echo "Cache Disabled"
+
+    # Uncached copy of the source we build.
+    DO +COPY_SRC
+
+    # Generate Checksums of the source
+    DO +FINGERPRINT_SRC --FINGERPRINT=src_fingerprint_uncached.txt
+
+    RUN diff ../src_fingerprint.txt ../src_fingerprint_uncached.txt \
+        || (echo "ERROR: Source fingerprints do not match. Caching Error Detected!!" && exit 1) \
+        && echo "Source fingerprints match. Caching OK."
 
 
 # local-ci-run: This step simulates the full CI run for local purposes only.
